name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build --if-present
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          MYSQL_DATABASE_NAME: ${{ secrets.MYSQL_DATABASE_NAME }}
          LOCAL_MYSQL_USERNAME: ${{ secrets.LOCAL_MYSQL_USERNAME }}
          LOCAL_MYSQL_PASSWORD: ${{ secrets.LOCAL_MYSQL_PASSWORD }}
          HUSKY: 0
        run: chmod +x script/prepare-release.sh && npx semantic-release